version: '3.6'
services:
  # stock_exchange_service:
  #   container_name: stock_exchange_service
  #   build:
  #     context: server/
  #     dockerfile: Dockerfile.stock_exchange_service
  #   depends_on:
  #     - db
  #   ports:
  #     - "8001:8001"

  db:
    container_name: db
    image: postgres:latest
    env_file: 
      - db.env
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432